spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      pool-name: TicketHikariCP

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    repair-on-migrate: true # Add this line to auto-repair checksum mismatches

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    com.ticketing: DEBUG
    org.springframework.security: INFO

app:
  upload-dir: ./uploads/
  auth:
    remember-me-key: ticketSystemSecureRememberMeKey
    remember-me-validity-seconds: 604800 # 7 days
